channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pyinstaller
  - pyqt
  - pywin32
  # test
  - flake8>=3.9
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-mutable
  - flake8-quotes
  - pep8-naming
  - pytest>=6.2
  - pytest-flake8
  # pip
  - pip>=21.1
  - pip:
    - --editable .
