channels:
  - conda-forge
dependencies:
  - conda-forge::python>=3.7
  - conda-forge::pyinstaller
  - conda-forge::pyqt
  - conda-forge::pywin32
  # test
  - conda-forge::flake8
  - conda-forge::flake8-builtins
  - conda-forge::flake8-comprehensions
  - conda-forge::flake8-import-order
  - conda-forge::flake8-mutable
  - conda-forge::flake8-quotes
  - conda-forge::pep8-naming
  # pip
  - conda-forge::pip
  - pip:
    - --editable .
