channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pyinstaller
  - pyqt
  - pywin32
  # test
  - flake8<5
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-mutable
  - flake8-quotes
  - pep8-naming
  - pytest
  - pytest-flake8
  # pip
  - pip
  - pip:
    - --editable .
